services:
  db:
    image: postgres:18
    container_name: sakila_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sakila
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sakila"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build: ./web
    container_name: sakila_web
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:1234@db:5432/sakila

volumes:
  pg_data: